name: Move Issues on Assignment

on:
  issues:
    types: [assigned, unassigned]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue
        if: github.event.action == 'assigned'
        uses: actions/github-script@v5
        with:
          script: |
            const columnId = 'Assigned'; // replace with actual column ID
            const issueId = context.issue.number;
            await github.projects.moveCard({
              card_id: columnId,
              position: 'top',
              column_id: issueId
            });
      - name: Move issue back
        if: github.event.action == 'unassigned'
        uses: actions/github-script@v5
        with:
          script: |
            const columnId = 'Contributors Needed'; // replace with actual column ID
            const issueId = context.issue.number;
            await github.projects.moveCard({
              card_id: columnId,
              position: 'top',
              column_id: issueId
            });
